name: Manual test

on:
  workflow_dispatch:
    inputs:
      reason:
        description: '触发原因'
        required: false
        default: '手动触发'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        run: |
          rm -rf *
          
      - name: Checkout Gitee repository
        run: |
          git clone https://gitee.com/song_of_light/weixin-chat.git
