name: Webhook Trigger Auto PR

on:
  repository_dispatch:
    types: [webhook-event]

jobs:
  run-auto-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gitee repository
        run: |
          git clone https://song_of_light:${{ secrets.GITEE_PASSWORD }}@gitee.com/song_of_light/obsidian-i18n-translation.git
          cd obsidian-i18n-translation

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Configure Git
        run: |
          git config --global user.name "曲淡歌"
          git config --global user.email "623009848@qq.com"

      - name: Run Auto PR script
        env:
          GITEE_ACCESS_TOKEN: ${{ secrets.GITEE_ACCESS_TOKEN }}
        run: |
          python auto_pr.py
