name: Webhook Trigger

on:
  repository_dispatch:
    types: [webhook-event]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run your action
        run: |
          echo "Action triggered by webhook"
          # 在这里添加您想要执行的命令
